### ISSUE TITLE
The Last Guardian patch stopped working

### ISSUE THREAD

**Issue by akuson94** [illusion0001/libhijacker#16]
I'm not sure what changed but the last guardian 4k 60 fps patch stopped working on the latest releases with rest mode support. I was able to use it before.

**Comment by edmaren** [comment]
It doesn't work for me with any release (I've tested several of the earliest and latest ones). 60 fps message shows up but the patch does nothing. 1.03 EUR version.

**Comment by illusion0001** [comment]
If you have kstuff, that's the issue
