### ISSUE TITLE
Debug mode patch for Bloodborne

### ISSUE THREAD

**Issue by LibretroAdmin** [illusion0001/libhijacker#26]
Could a debug mode patch for Bloodborne be added? The debug mode patch exists somewhere. It could simply be stubbed out (#if 0) so that developers could stub it out, recompile it from source and then use it. It doesn't necessarily have to be exposed to endusers by default, just so long as power users are able to enable it for themselves with their own compiled libhijacker.

Debug mode can be seen here in action, this is normally achieved editing the eboot.bin.

https://www.youtube.com/watch?v=pT0PKsLEcss

This could help greatly with modding work on the game.

**Comment by illusion0001** [comment]
Needs shaders and font files not present in retail game. You can patch eboot to open it but it will crash due to missing files.
