### ISSUE TITLE
Just Cause 3

### ISSUE THREAD

**Issue by mmcgr97** [illusion0001/libhijacker#30]
Does anyone know when Just Cause 3 60fps will be added. I saw it in the Digital Foundry video yet it doesn't seem to be publicly available.

**Comment by illusion0001** [comment]
The patch was here, I forgot to update the Readme.
https://github.com/illusion0001/libhijacker/blob/4e54cfddc2c72f28300697cbdd8c07c7e21066a9/daemon/source/game_patch_thread.cpp#L572-L581
